function Hd = gyroscopeFilter
%GYROSCOPEFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 19-Apr-2019 12:23:01

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 0.5;  % Sampling Frequency

Fstop = 0.0014285714286;  % Stopband Frequency
Fpass = 0.002;            % Passband Frequency
Dstop = 0.0001;           % Stopband Attenuation
Dpass = 0.057501127785;   % Passband Ripple
dens  = 20;               % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
