function Hd = gyroscopeFilter
%GYROSCOPEFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.4 and DSP System Toolbox 9.6.
% Generated on: 03-Feb-2019 17:00:13

% Chebyshev Type II Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 0.5;  % Sampling Frequency

N      = 20;      % Order
Fstop1 = 0.0005;  % First Stopband Frequency
Fstop2 = 0.01;    % Second Stopband Frequency
Astop  = 80;      % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandpass('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
